In [1]:
import tensorflow as tf
import os

In [2]:

t1 = tf.constant(1.0, shape=[3,3,3])
tf.assert_negative(t1)
    
init = tf.initialize_all_variables()

sess = tf.Session()
sess.run(init)
t1_val = sess.run(t1)


In [3]:
print t1_val

[[[ 1.  1.  1.]
  [ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]
  [ 1.  1.  1.]]]
